Alimentalos/Backend

- app/Events/GeofenceIn.php
- app/Events/GeofenceOut.php
- app/Events/Location.php
- app/Http/Controllers/Api/Comments/DestroyController.php
- app/Http/Controllers/Api/Devices/IndexController.php
- app/Http/Controllers/Api/Geofences/DestroyController.php
- app/Http/Controllers/Api/Groups/DestroyController.php
- app/Http/Controllers/Api/Pets/UpdateController.php
- app/Http/Controllers/Api/Photos/DestroyController.php
- app/Http/Controllers/Api/Users/DestroyController.php
- app/Http/Controllers/Api/Users/UpdateController.php
- app/Http/Controllers/HomeController.php
- app/Providers/AuthServiceProvider.php
- app/Providers/EventServiceProvider.php
- app/Repositories/UploadRepository.php
- app/User.php
> Complexity reduced.

- app/Http/Controllers/Api/Groups/UpdateController.php
- app/Http/Controllers/Api/Pets/UpdateController.php
- app/Repositories/GroupsRepository.php
- app/Repositories/HandleBindingRepository.php
- app/Repositories/LoggerRepository.php
- app/Repositories/PetsRepository.php
- app/Repositories/PhotoRepository.php
- app/Repositories/SubscriptionsRepository.php
- app/Repositories/UploadRepository.php
With this merge, backend code is scrutinized with code climate and complaints with their code change recommends.
> Perfect code quality

- README.md
> Badge added.

- tests/Feature/Api/UserTest.php
Tests was updated and increased the number of asserts.
> Testing improved

- app/User.php
- database/factories/UserFactory.php
- tests/Feature/Stories/GroupAdministratorCanUpdateGroupPhotoTest.php
This PR want fix the build pipelines.
> [2.1] Fix codecov pipeline

- app/Annotations/Base.php
- relationships/src/Procedures/DeviceProcedure.php
- relationships/src/Procedures/UserProcedure.php
- relationships/src/Resources/DeviceResource.php
- relationships/src/Resources/UserResource.php
- storage/api-docs/api-docs.json
- tests/Feature/Stories/UserCanCreateChildUsersWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreateChildUsersWithoutMarkerTest.php
- tests/Feature/Stories/UserCanCreateChildUsersWithoutPhotoTest.php
- tests/Feature/Stories/UserCanCreateDevicesWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreateDevicesWithoutMarkerTest.php
This PR will be add more flexible user stories. 
Now you can create resources without all the parameters like child users without photos or colors.
That's can be great to create min-data of resources.
> 9.4 - More flexible stories

- app/tools.php
- relationships/src/Procedures/DeviceProcedure.php
- relationships/src/Procedures/GeofenceProcedure.php
- relationships/src/Procedures/GroupProcedure.php
- relationships/src/Procedures/PetProcedure.php
- relationships/src/Procedures/PhotoProcedure.php
- relationships/src/Procedures/PlaceProcedure.php
- relationships/src/Procedures/UserProcedure.php
- relationships/src/Repositories/AlertsRepository.php
- relationships/src/Resources/AccessResource.php
- relationships/src/Resources/ActionResource.php
- relationships/src/Resources/AlertResource.php
- relationships/src/Resources/CommentResource.php
- tools/src/Uploader.php
This PR will be add some code refacts, less lines required and better procedure logics.
> 9.5 - Code refacts

- relationships/src/Resources/GeofenceResource.php
- relationships/src/Resources/GroupResource.php
- relationships/src/Resources/PetResource.php
- relationships/src/Resources/PlaceResource.php
- tests/Feature/Stories/UserCanCreateGeofenceWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreateGeofenceWithoutMarkerTest.php
- tests/Feature/Stories/UserCanCreateGeofenceWithoutPhotoTest.php
- tests/Feature/Stories/UserCanCreateGroupsWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreateGroupsWithoutPhotoTest.php
- tests/Feature/Stories/UserCanCreatePetsWithoutPhotoTest.php
- tests/Feature/Stories/UserCanCreatePlacesWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreatePlacesWithoutMarkerTest.php
- tests/Feature/Stories/UserCanCreatePlacesWithoutPhotoTest.php
Some resources actually needs many properties to works great. 
Now just specific resource properties will be required.
> 9.6 - More flexible user cases.

- app/Annotations/Base.php
- relationships/src/Observers/DeviceObserver.php
- relationships/src/Observers/GroupObserver.php
- relationships/src/Observers/PetObserver.php
- relationships/src/Observers/PhotoObserver.php
- relationships/src/Observers/PlaceObserver.php
- relationships/src/Observers/UserObserver.php
- relationships/src/Procedures/DeviceProcedure.php
- relationships/src/Procedures/GroupProcedure.php
- relationships/src/Procedures/PetProcedure.php
- relationships/src/Procedures/PhotoProcedure.php
- relationships/src/Procedures/PlaceProcedure.php
- relationships/src/Procedures/UserProcedure.php
- storage/api-docs/api-docs.json
- tests/Feature/Stories/UserCanCreateDevicesTest.php
- tests/Feature/Stories/UserCanCreateDevicesWithoutColorsTest.php
- tests/Feature/Stories/UserCanCreateDevicesWithoutMarkerTest.php
- tests/Feature/Stories/UserCanCreateGeofenceUsingPhotoAndStringShapeTest.php
- tests/Feature/Stories/UserCanCreateGroupsTest.php
Colors apparently don't work successfully. 
I have to add some color filling fixes.
> 9.7 - Color testing

- app/Http/Requests/Api/RegisterRequest.php
- database/migrations/2020_02_27_072003_create_photos_table.php
- database/migrations/2020_02_27_072318_create_alerts_table.php
- database/migrations/2020_02_27_072318_create_places_table.php
- relationships/src/Procedures/AlertProcedure.php
- relationships/src/Procedures/PhotoProcedure.php
- relationships/src/Procedures/PlaceProcedure.php
- relationships/src/Resources/AlertResource.php
- relationships/src/Resources/GeofenceResource.php
- relationships/src/Resources/GroupResource.php
- relationships/src/Resources/PetResource.php
- relationships/src/Resources/PhotoResource.php
- relationships/src/Resources/PlaceResource.php
- relationships/src/Resources/UserResource.php
- relationships/src/Rules/Coordinate.php
- tests/Feature/Stories/UserCanCreateChildUsersWithPhotoAndWithoutCoordinatesTest.php
- tests/Feature/Stories/UserCanCreateGeofenceWithPhotoAndStringShapeTest.php
- tests/Feature/Stories/UserCanCreateGeofenceWithPhotoAndWithoutCoordinatesTest.php
- tests/Feature/Stories/UserCanCreateGeofenceWithPhotoTest.php
- tests/Feature/Stories/UserCanCreateGroupsWithPhotoAndWithoutCoordinatesTest.php
- tests/Feature/Stories/UserCanCreatePetAlertsWithoutCoordinatesTest.php
- tests/Feature/Stories/UserCanCreatePetsWithoutCoordinateTest.php
- tests/Feature/Stories/UserCanCreatePlacesWithPhotoAndWithoutCoordinatesTest.php
- tools/src/Uploader.php
> Ubicación ya no será requerida

- .idea/codeStyles/codeStyleConfig.xml
- app/Http/Controllers/Api/Near/Resource/IndexController.php
> Null locations will be ignored

- resources/views/layouts/base.blade.php
- resources/views/welcome.blade.php
> Estrucura HTML5 mejorada 

- resources/views/welcome.blade.php
> Sección de inicio mejorada 

- resources/views/welcome.blade.php
> Sección de mascotas adoptadas responsive mejorado 

- resources/views/welcome.blade.php
> Responsive mejorado sección contacto 

- resources/views/welcome.blade.php
> Footer resposive mejorado 

- resources/views/pets/create.blade.php
> Formulario añadido en el archivo correcto.

- resources/views/pets/edit.blade.php
> Formulario de editar mascotas añadido 

- resources/views/pets/index.blade.php
> index de mascotas añadido 

- resources/views/pets/show.blade.php
> Mostrar mascota añadido 

- resources/views/groups/create.blade.php
> Formulario crear grupo añadido 

- resources/views/groups/edit.blade.php
> Formulario editar grupo añadido 

- resources/views/groups/show.blade.php
> Mostrar grupo añadido

- resources/views/groups/index.blade.php
> Index de grupos añadido

- resources/views/pets/index.blade.php
> vista index de mascotas mejorada 

- resources/views/geofences/create.blade.php
> Formulario crear geocerca mascota 

- resources/views/places/create.blade.php
> Formulario crear lugar añadido 

- resources/views/devices/create.blade.php
> Formulario crear dispositivo añadido 

- resources/views/devices/edit.blade.php
> Formulario editar dispositivo añadido 

- resources/views/geofences/edit.blade.php
> Formulario editar geocerca mascota añadida 

- resources/views/devices/index.blade.php
> Index de dispositivos añadido 

- resources/views/places/index.blade.php
> Index de lugares añadido 

- resources/views/geofences/index.blade.php
> Index de geocercas añadido 

- .github/workflows/quasar.yml
- cordova/package.json
> Quasar pipeline added.
